**1. Импорт библиотеки NumPy с общепринятым сокращением.**

In [1]:
import numpy as np  # Импорт библиотеки NumPy с сокращением np

**2. Примеры создания массивов:**
- из обычных списков;
- с использованием функций `zeros`, `ones`, `arange` или аналогичных.

In [2]:
arr_list = np.array([1, 2, 3, 4, 5]) # Создание массива из обычного списка
arr_list


array([1, 2, 3, 4, 5])

In [5]:
arr_zeros = np.zeros((5, 5)) # Создание двумерного массива из нулей размером 5 на 5
arr_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
arr_ones = np.ones(3) # Создание одномерного массива из единиц длиной 3 элемента
arr_ones

array([1., 1., 1.])

In [7]:
arr_range = np.arange(1, 20, 4) # Создание массива с использованием range
arr_range

array([ 1,  5,  9, 13, 17])

**3. Демонстрация атрибутов:**
- вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [3]:
type(arr_zeros) # Отображение типа данных массива с нулями

numpy.ndarray

In [4]:
arr_zeros.shape # Отображние формы массива с нулями

(5,)

`arr_zeros` является двумерным массивом размером 5 на 5.

**4. Примеры индексирования и срезов:**
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.

In [9]:
arr_range

array([ 1,  5,  9, 13, 17])

In [8]:
element = arr_range[2] # Получение третьего элемента массива (с индексом 2)
element

np.int64(9)

In [24]:
slice_arr = arr_range[0:3] # Получение подмассива с первого по третий элемент
slice_arr

array([1, 5, 9])

**5. Примеры векторных операций и базовых статистик:**
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

In [13]:
arr_list

array([1, 2, 3, 4, 5])

In [14]:
arr_range

array([ 1,  5,  9, 13, 17])

In [15]:
arr_sum = arr_list + arr_range # Получение поэлементной суммы массивов
arr_sum

array([ 2,  7, 12, 17, 22])

In [17]:
arr_mul = arr_list * arr_range # Получение поэлементного перемножения массивов
arr_mul

array([ 1, 10, 27, 52, 85])

In [25]:
mean_value = arr_mul.mean() # Получение среднего значения массива arr_mul
mean_value

np.float64(35.0)